
DEFAULT_PANEL_WATTAGE_W = 450          
DEFAULT_PANEL_AREA_SQFT = 22.0         
DEFAULT_DERATE_FACTOR = 0.82
DEFAULT_TILT_DEGREES = None           
DEFAULT_AZIMUTH_DEGREES = 180.0
DEFAULT_AUTONOMY_DAYS = 1              
DEFAULT_BATTERY_DOD = 0.80             
DEFAULT_BATTERY_EFFICIENCY = 0.90      
DEFAULT_BATTERY_CAPACITY_KWH = 5.0     
DEFAULT_SYSTEM_VOLTAGE = 48            
DEFAULT_INVERTER_SAFETY_FACTOR = 1.25  
DEFAULT_COST_PER_KW_INR = 60000        
DEFAULT_BATTERY_COST_INR = 25000       
DEFAULT_SIZING_SAFETY_FACTOR = 1.10